on: "push"

name: PR-CI-gated

jobs:
  build:
    name: gated
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install terraform v1.0.5
        uses: little-core-labs/install-terraform@v2.0.0
        with:
            version: 1.0.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: validate tf config
        run: | 
          export VH_ROOT=$(scripts/get-root)
          cd "${VH_ROOT}/terraform"
          terraform init
          terraform validate
      
      - name: validate build
        run: scripts/build

